version: '3'

services:
  envoy:
    build: ./envoy
    ports:
      - "9901:9901"
      - "10000:10000"
    env_file: .env
    profiles: ["debug", "dev"]

  session_server:
    build: ./session_service
    ports:
      - "50051:50051"
    env_file: .env
    depends_on: ["envoy"]
    profiles: ["debug", "dev"]