version: '3'

services:
  evans_cli:
    build: 
      context: ./
      dockerfile: ./evans_cli/Dockerfile
    tty: true

  session_server:
    build: 
      context: ./
      dockerfile: ./session_service/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./session_service/src:/usr/src/app
      - /usr/src/app/common # Ignores common files
      - /usr/src/app/node_modules # Ignores node_modules

  envoy:
    image: envoyproxy/envoy-dev:7e6986f75b952aae4d9048b16ca90e6494ca3bf7
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./envoy:/etc/envoy